{{- if .Values.ai.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: synstream-ai
  labels:
    {{- include "synstream.componentLabels" (dict "name" "synstream-ai" "workloadType" "statefulset" "Chart" .Chart "Release" .Release) | nindent 4 }}
  {{- with .Values.ai.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.ai.service.type }}
  ports:
    - port: {{ .Values.ai.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "synstream.componentSelectorLabels" (dict "name" "synstream-ai") | nindent 4 }}
{{- end }}

