{{- if and .Values.ai.enabled .Values.ai.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "synstream.componentServiceAccountName" (dict "component" .Values.ai "name" "ai") }}
  labels:
    {{- include "synstream.componentLabels" (dict "name" "synstream-ai" "workloadType" "statefulset" "Chart" .Chart "Release" .Release) | nindent 4 }}
  {{- with .Values.ai.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.ai.serviceAccount.automount }}
{{- end }}

