{{- if and .Values.auth.enabled .Values.auth.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "synstream.componentServiceAccountName" (dict "component" .Values.auth "name" "auth") }}
  labels:
    {{- include "synstream.componentLabels" (dict "name" "synstream-auth" "workloadType" "statefulset" "Chart" .Chart "Release" .Release) | nindent 4 }}
  {{- with .Values.auth.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.auth.serviceAccount.automount }}
{{- end }}

