{{- if and .Values.console.enabled .Values.console.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "synstream.componentServiceAccountName" (dict "component" .Values.console "name" "console-vite") }}
  labels:
    {{- include "synstream.componentLabels" (dict "name" "synstream-console-vite" "workloadType" "deployment" "Chart" .Chart "Release" .Release) | nindent 4 }}
  {{- with .Values.console.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.console.serviceAccount.automount }}
{{- end }}
