{{- if .Values.reverseProxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: synstream-reverse-proxy
  labels:
    {{- include "synstream.componentLabels" (dict "name" "synstream-reverse-proxy" "workloadType" "deployment" "Chart" .Chart "Release" .Release) | nindent 4 }}
  {{- with .Values.reverseProxy.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.reverseProxy.service.type }}
  ports:
    - port: {{ .Values.reverseProxy.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "synstream.componentSelectorLabels" (dict "name" "synstream-reverse-proxy") | nindent 4 }}
{{- end }}

