{{- if and .Values.reverseProxy.enabled .Values.reverseProxy.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "synstream.componentServiceAccountName" (dict "component" .Values.reverseProxy "name" "reverse-proxy") }}
  labels:
    {{- include "synstream.componentLabels" (dict "name" "synstream-reverse-proxy" "workloadType" "deployment" "Chart" .Chart "Release" .Release) | nindent 4 }}
  {{- with .Values.reverseProxy.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.reverseProxy.serviceAccount.automount }}
{{- end }}

