apiVersion: v2
name: synstream-manager
description: SynStream Manager service for flow and license management
type: application
version: 0.1.5
appVersion: "v0.0.1"
home: https://rtsinv.com
maintainers:
  - name: Jose Wang
    email: jose@rtsinv.com
keywords:
  - synstream
  - manager
